const COURSE_CATEGORY_TYPES = {
  ACADEMIC: "ACADEMIC",
  PERSONAL_DEVELOPMENT: "PERSONAL_PERSONAL_DEVELOPMENT",
  BUSINESS_AND_PROFESSIONAL: "BUSINESS_AND_PROFESSIONAL",
  ART_AND_DESIGN: "ART_AND_DESIGN",
  TECHNOLOGY: "TECHNOLOGY",
  LIFE_STYLE: "LIFE_STYLE",
};

module.exports = COURSE_CATEGORY_TYPES;
